### ISSUE TITLE
How to Fix "ImportError: libGL.so.1: cannot open shared object file" Issue

### ISSUE THREAD

**Issue by Brandon-c-tech** [yeates/PromptFix#13]
If you encounter this issue:
如果你遇到了这个问题：

Traceback (most recent call last):
  File "/root/PromptFix/scripts/../process_images_json.py", line 23, in <module>
    from stable_diffusion.ldm.hfp import extract_high_freq_component, sobel_operator
  File "/root/PromptFix/stable_diffusion/ldm/hfp.py", line 2, in <module>
    import cv2
  File "/opt/conda/envs/promptfix/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/opt/conda/envs/promptfix/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/opt/conda/envs/promptfix/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

This can resolve it.
这可以解决：
```
apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0
```

**Comment by yeates** [comment]
Thanks for sharing this!!
